### ISSUE TITLE
Function to render html

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#112]
Hello, 

I would like to render a static HTML file and/or a Jinja Template as a response to a Cloud Function using the `@app.route('/')` decorator. Is there an easy way to do it ?

Thanks !

**Comment by anovis** [comment]
I believe it should be doable using the [Response class](https://anovis.github.io/goblet/docs/build/html/topics.html#response), which is simply a flask response object. 

[This article](https://medium.com/@tim_33529/creating-a-serverless-blog-with-chalice-bdc39b835f75) has some good information on rendering a jinja template in chalice, which is what goblet is based on.

Let me know if this is helpful, or if there are any changes I would need to add.

**Comment by amirbtb** [comment]
I'm blocked by #113
