### ISSUE TITLE
Create multiple cloud functions by passing in entryfile

### ISSUE THREAD

**Issue by anovis** [anovis/goblet#115]
add `config` entry that allows any file to become the `main.py` file and therefore allow for multiple functions to be deploying using similar code bases. (#90 )

for example with the following files
```
func1.py
func2.py
shared.py
```

we could have the goblet `.config`
```
{
    "stages": {
        "func1": {
            "function_name": "func1",
            "main_file" : "func1"

        },
        "func2": {
            "function_name": "func2",
            "main_file" : "func2"
    }
}
```

and behind the scenes the file is renamed to `main.py`

note this may cause some imports to break if something is importing from the `func1.py` or `func2.py`

**Comment by amirbtb** [comment]
Thank you for this proposal.

This is exactly what I had in mind when I opened #90. It's similar to a [feature in Chalice](https://aws.github.io/chalice/topics/configfile.html#per-lambda-examples)

Your remark about breaking imports could be problematic in case of tests importing cloud functions. Nevertheless, if the logic is in library code (which is testable ; that's what I'm currently doing), that's not a problem.

**Comment by anovis** [comment]
The tests should actually work as expected, since the name change occurs during deploy time.

Let me know if #116 works for your use case. i tested all cli commands including local, deploy, delete and seems to be working as expected with the new `main_file` keyword. The one issue, which i have not been able to resolve is the deploy seems to not update correctly if there is a `main.py` in the folder along with the file you specify with `main_file` even though the zips look ok in the console + locally. I will look into it, but in the meantime everything else seems to work.
