### ISSUE TITLE
[Cloudrun backend] Missing None. Make sure you are in the correct directoty and this file exists

### ISSUE THREAD

**Issue by mikaelcoumet** [anovis/goblet#143]
Hi,
first of all, thanks for your work !
I use Goblet for cloud functions and it's very simple.
But when I try to use cloud run  as a backend, I have the error :
`"Missing None. Make sure you are in the correct directoty and this file exists" `
while I have a main.py and a dockerfile in the directory.

Any idea of what can be the issue ?
Thanks in advance,
Regards

**Comment by anovis** [comment]
Hmm usually it is because `main.py` is missing and the error will be `Missing main.py`, which doesn't seem the case this time. 
It could be am issue with `config.json`. it will need to have a section for cloudrun instead of cloudfunction.

**Comment by amirbtb** [comment]
Hi !
Maybe you are missing a key in the `config.json`. Indeed, the required configuration for cloudrun backend isn't clear. Are there required keys to put both inside and outside the `"cloudrun"` key ?
It would be great to have an example of a standard config for the cloudrun backend, such as the [config section of the goblet documentation](https://anovis.github.io/goblet/docs/build/html/topics.html#config).

**Comment by anovis** [comment]
@mikaelcoumet I used the config and I did get a different error related to `no-allow-authenticated`. That looks to be my mistake. It should be `no-allow-unauthenticated`. It actually defaults to `no-allow-unauthenticated` so you can remove that line from the config. let me know if that works for you.

**Comment by anovis** [comment]
I had tried to add an example `https://raw.githubusercontent.com/anovis/goblet/master/docs/source/backends.rst` but looks like the docs are not rendering correctly. will take a look at that and also update the section that @amirbtb referenced

**Comment by anovis** [comment]
the deploy worked with
 ```{
    "cloudrun":{
        "max-instances": "1",
        "set-env-vars": "ENV1=env1"
    }
}
```
if you created with goblet init. i did have to add `goblet_entrypoint`

```
from goblet import Goblet, jsonify, goblet_entrypoint

app = Goblet(function_name="goblet-test-func", backend="cloudrun")
goblet_entrypoint(app)
```

i will work on updated the docs and `goblet init`
