### ISSUE TITLE
Error when deploying a Cloud Function to a GCP project when Eventarc API isn't enabled

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#156]
## Description

Hello, 

I try to deploy a Cloud Function with a `@app.schedule()` to a GCP project where the Eventarc API is not enabled (because I don't need to use it). I get this error : 
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://eventarc.googleapis.com/v1/projects/my-awesome-project/locations/europe-north1/triggers?alt=json returned "Eventarc API has not been used in project 538837563781 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/eventarc.googleapis.com/overview?project=538837563781 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems an and retry.". 
Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/eventarc.googleapis.com/overview?project=538837563781'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'service': 'eventarc.googleapis.com', 'consumer': 'projects/538837563781'}}]">
```
Is there still a way to deploy a Cloud Function using goblet without having to enable the Eventarc API ? Thank you !

## Environments details 
- **goblet version** : 0.7.0
- **Python version** : 3.7
- **Docker environment** : yes

**Comment by anovis** [comment]
Hmm you shouldn't need to have it enabled. The only case could be in the goblet sync command, so i will look into that. 

Do you mind sharing more on the commands used. Was it on goblet deploy?

**Comment by amirbtb** [comment]
Yes you are totally right, I used `goblet sync` (I forgot that I was using it since I'm using a CLI command that wraps both `goblet sync` and `goblet deploy`)

**Comment by anovis** [comment]
cool. will get a fix for that in tonoght
