### ISSUE TITLE
Allow other files in zip along with *.py files

### ISSUE THREAD

**Issue by ivmarkp** [anovis/goblet#16]
Config parameters are usually stored in `.ini` or `.txt` files. Can we allow `.ini` and `.txt` files atleast?

https://github.com/anovis/goblet/blob/61a8ce2e4e1ff8d3967d79437573843f5c88c389/goblet/deploy.py#L157

**Comment by anovis** [comment]
@ivmarkp thats a good callout. I will make sure to add those in the next release. in the meantime you can add those files using the `customFiles` key in `config.json`

```
{
    "customFiles": ["*.ini", "*.txt"]
}
```

**Comment by ivmarkp** [comment]
Thanks, that worked.

Also, thanks for goblet. It's really helpful. I'm surprised gcp doesn't have anything official like aws chalice.

**Comment by anovis** [comment]
you are very welcome. I appreciate it. 

Also feel free to let me know if you have any suggestions for features or anything else you would like to see in goblet

**Comment by ivmarkp** [comment]
I would say documentation of Request and Response should list common fields with their description and an example e.g. headers, method, json body etc.

Also, it would be better to have Response object provided by goblet just like [chalice does](https://aws.github.io/chalice/api.html#response). `Goblet.jsonify` is great but using it as `app.jsonify` doesn't seem right because one has to move app object around in the application code.

**Comment by anovis** [comment]
thanks for those suggestions. added Response class that should help with custom headers and moved jsonify out of the Goblet class. also linked to better documentation for the flask response and request fields. thanks for using the project!

**Comment by ivmarkp** [comment]
Thank you! Appreciate it a lot.
