### ISSUE TITLE
Deployer triggering scheduled function deployment without any scheduled job in codebase

### ISSUE THREAD

**Issue by ivmarkp** [anovis/goblet#18]
Hello again ~ 

Is this expected from deployer? Earlier I didn't encounter this issue.

**Comment by anovis** [comment]
ah let me check. I do not think it is actually deploying anything, but will double check. from a quick glance it looks like it is outputting `deploying scheduled functions......` , but then only deploys the function if there is a scheduled job. I will go ahead and show that line only if there is a scheduled job going forward.
