### ISSUE TITLE
[Secret Manager] Secret Manager Integration

### ISSUE THREAD

**Issue by anovis** [anovis/goblet#58]
A built in integration with [Secret Manager](https://cloud.google.com/secret-manager) to inject secrets into cloudfunctions. Currently the options are to supply env variable, or to write the secret manager logic yourself. 

example config.json

```
"secrets": {
  "GH_TOKEN": projects/{project_id}/secrets/GH_TOKEN/versions/2",
  "OTHER_TOKEN"
}
```
with default being `projects/{project_id}/secrets/{secret_name}/versions/latest`

then in your code you would use `config.secrets` to access

```
from goblet.config import Config

config = Config()
@app.route("/reveal")
def reveal_secret():
    return config.secrets.GH_TOKEN
```

**Comment by anovis** [comment]
https://cloud.google.com/blog/products/serverless/cloud-functions-integrates-with-google-secret-manager

**Comment by anovis** [comment]
looks like it is only supported for gcloud cli and the console for now. will continue to monitor for the v1beta api to include this feature

**Comment by aebrahim** [comment]
FYI https://github.com/googleapis/python-functions/pull/130

**Comment by anovis** [comment]
interesting. goblet actually calls the rest api directly via https://cloud.google.com/functions/docs/reference/rest, so i am wondering if there is another library that handles the secret volumes

**Comment by amirbtb** [comment]
Looks like secrets in Cloud Functions are finally in GA 🥳 
[GCP Release Notes](https://cloud.google.com/release-notes#January_25_2022)

**Comment by anovis** [comment]
Interestingly, goblet supports secrets already with the `cloudrun` backend since we actually use a gcloud command behind the scenes to build and deploy the container. 

will continue to look into secret support for the `cloudfunction` backend

**Comment by anovis** [comment]
looks like secrets are added to v1 endpoints now https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions
