### ISSUE TITLE
Create multiple cloud scheduler to call the same function

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#91]
Hello,

I am working on a simple use case : I have a cloud function that accepts a 'URl' parameter, calls that URl (which is a public API endpoint) and saves the data in a JSON file stored in Cloud Storage. I want to be able to set multiple cloud scheduler to call different endpoints on different schedules, but I only need 1 function.

Question : My guess is that `@app.schedule('5 * * * *')` creates both a Cloud Scheduler and a Cloud Function. Is there a possibility to only create a (or multiple) Cloud Scheduler and define parameters to use in the call to the Cloud Function ?

**Comment by anovis** [comment]
You are correct that the `@app.schedule('5 * * * *')` will create both the cloud function and the cloud scheduler. If you would like multiple schedules for the same function then you simply add additional decorators. having multiple schedules and multiple functions will still only create one http cloudfunction. 

```
@app.schedule('5 * * * *')
@app.schedule('2 * * * *')
def scheduled_function(app.request)
...


@app.schedule('3 * * * *')
def scheduled_function2(app.request)
...
```

Right now `app.scheduler` doesn't take in any additional parameters, but it looks like a Scheduler Job [http_target ](https://cloud.google.com/scheduler/docs/reference/rest/v1/projects.locations.jobs#HttpTarget) supports a body, method, and additional headers, so will work on a pr this week to support that.

**Comment by amirbtb** [comment]
Thank you for your promptness, can't wait to try this feature !!

**Comment by anovis** [comment]
@amirbtb take a look at the latest release `0.5.0` and see if that solves your use case.

**Comment by amirbtb** [comment]
Hello, thank you for this feature it looks perfect on the paper. I will try it tomorrow and keep you updated.

**Comment by amirbtb** [comment]
I used the `body` argument of `@app.schedule()` in order to **POST**  a dict to the cloud function. I managed to encode my dict into a base64 string but the process is tedious : 
I give `base64.b64encode(json.dumps({"key":"value"}).encode('utf-8')).decode('ascii')` to the `body` argument, then in my function in order to convert the base64 string into a python dict I use `json.loads(base64.b64decode(raw_payload).decode('utf-8'))`.

Nonetheless, the Cloud Scheduler is created and it is working fine ! 🥳 

I noticed the Cloud Scheduler had some parameters, like `name` `description` `timeZone` `retryConfig` and  `attemptDeadline` set  to default values by Goblet but they could be useful. Do you want me to create an issue for this ?

**Comment by anovis** [comment]
thats good to hear! Unfortunately i am not able to make the `body` any simpler since it is gcp that requires a base66 encoded string. 

in terms of the additional configs, `description` and `timeZone` are already available.

`name` is generated by goblet right now since it needs to be unique and is based on the cloud function name as well as the function name it is decorated, so I am not sure if I want that to be configurabe.

I can certainly add overrides for `retryConfig` and `attemptDeadline` if you don't mind making another issue for those.

**Comment by amirbtb** [comment]
> thats good to hear! Unfortunately i am not able to make the `body` any simpler since it is gcp that requires a base66 encoded string.

I understand. Maybe you want to add instructions about how to encode and decode using the `body` argument.

> in terms of the additional configs, `description` and `timeZone` are already available.

Perfect, I'm gonna use them right away !
 
> `name` is generated by goblet right now since it needs to be unique and is based on the cloud function name as well as the function name it is decorated, so I am not sure if I want that to be configurabe.

Using `app.scheduler()` multiple times for the same function creates multiple elements with similar names, it can be an issue. In the mean time, we can still use `description` in order to differentiate them.
<img width="539" alt="mutiple_cloudsched_names" src="https://user-images.githubusercontent.com/76230761/140563433-afb83f1f-dcfd-42a1-abe1-42a950281e5e.png">

> I can certainly add overrides for `retryConfig` and `attemptDeadline` if you don't mind making another issue for those.
On it. Thank you again for your reactivity !
